package lib

var (
	ServiceNames = []string{
		"appenricher",
		"carbonblackingest",
		"casemanager",
		"ciscoampingest",
		"classifier",
		"crowdstrikeingest",
		"cveinvestigator",
		"deduper",
		"domaininvestigator",
		"emailer",
		"eventscorer",
		"fileinvestigator",
		"firewallresponse",
		"hosttracker",
		"ipinvestigator",
		"ja3hashinvestigator",
		"logfinder",
		"mistwatcher",
		"networkinvestigator",
		"oktalogsimport",
		"packetserver",
		"rapid7investigator",
		"reporter",
		"sentineloneingest",
		"servicenowintegration",
		"splunkwatcher",
		"urlinvestigator",
		"usertracker",
		"windowsdefenderingest",
	}
)
