name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**' # This will trigger on all branches
  release:
    types:
      - created
    branches:
      - main_prod

jobs:
  build:
    runs-on: windows-latest
    name: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install --peer-deps

      - name: Build project
        run: npm run build
